version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - ./database:/bitnami
    environment:
      - MONGODB_USERNAME=username
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=myapp
  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:8080'
    volumes:
      - ./site:/app
  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/express:latest'
    labels:
      kompose.service.type: nodeport
    command: npm run development
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://username:password@mongodb:27017/myapp
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
